---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, devel]
      - id: trailing-whitespace

  - repo: https://github.com/asottile/add-trailing-comma.git
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma
        args:
          - --py36-plus

  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.1
    hooks:
      - id: remove-tabs

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.0.0-alpha.6
  #   hooks:
  #     - id: prettier
  #       always_run: true
  #       additional_dependencies:
  #         - prettier
  #         - prettier-plugin-toml
  #         - prettier-plugin-sort-json

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.3.0"
    hooks:
      - id: tox-ini-fmt

  # - repo: https://github.com/charliermarsh/ruff-pre-commit
  #   rev: "v0.0.263"
  #   hooks:
  #     - id: ruff
  #       args:
  #         - "--exit-non-zero-on-fix"

  # - repo: https://github.com/streetsidesoftware/cspell-cli
  #   rev: v6.31.0
  #   hooks:
  #     - id: cspell
  #       name: Spell check with cspell

  # untill ruff has parity with darglint
  # - repo: https://github.com/PyCQA/flake8.git
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  #       language_version: python3
  #       additional_dependencies:
  #         - darglint
  #         - flake8-docstrings

  # - repo: https://github.com/pycqa/pylint.git
  #   rev: v3.0.0a6
  #   hooks:
  #     - id: pylint
  #       args:
  #         - --output-format=colorized

  # - repo: https://github.com/pre-commit/mirrors-mypy.git
  #   rev: v1.2.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         - pytest
  #         - tox
  #         - types-PyYAML
  #       args:
  #         - src
  #         - tests
  #         - --python-version=3.8
  #       pass_filenames: false
