# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
---

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: >-  # has to be parsed as a YAML string
      3.13
  commands:
  - >-
    PYTHONWARNINGS=error
    python3 -Im venv "${READTHEDOCS_VIRTUALENV_PATH}"
  - >-
    PYTHONWARNINGS=error
    "${READTHEDOCS_VIRTUALENV_PATH}"/bin/python -Im
    pip install tox
  - >-
    PYTHONWARNINGS=error
    "${READTHEDOCS_VIRTUALENV_PATH}"/bin/python -Im
    tox -e build-docs --notest -vvvvv
  - >-
    PYTHONWARNINGS=error
    "${READTHEDOCS_VIRTUALENV_PATH}"/bin/python -Im
    tox -e build-docs --skip-pkg-install -q
    --
    -D language="${READTHEDOCS_LANGUAGE}"
    "${READTHEDOCS_OUTPUT}"/html -b dirhtml
  - >-
    PYTHONWARNINGS=error
    "${READTHEDOCS_VIRTUALENV_PATH}"/bin/python -Im
    tox -e build-docs --skip-pkg-install -q
    --
    -D language="${READTHEDOCS_LANGUAGE}"
    "${READTHEDOCS_OUTPUT}"/pdf -b latex
  - cat "${READTHEDOCS_OUTPUT}"/pdf/latexmkrc
  - >-  # https://mg.rtfd.io/latexmk.html is a Perl script pre-installed on RTD
    cd "${READTHEDOCS_OUTPUT}"/pdf/
    &&
    latexmk -r latexmkrc
    -pdf -f -dvi- -ps-
    -jobname="${READTHEDOCS_PROJECT}"
    -interaction=nonstopmode
  - >-  # RTD requires only a single PDF file to be in the output directory
    find "${READTHEDOCS_OUTPUT}"/pdf
    -type f
    -not -name "${READTHEDOCS_PROJECT}.pdf"
    -delete
    &&
    find "${READTHEDOCS_OUTPUT}"/pdf
    -mindepth 1
    -type d
    -delete
    && ls -1 "${READTHEDOCS_OUTPUT}"/pdf
  - >-
    PYTHONWARNINGS=error
    "${READTHEDOCS_VIRTUALENV_PATH}"/bin/python -Im
    tox -e build-docs --skip-pkg-install -q
    --
    -D language="${READTHEDOCS_LANGUAGE}"
    "${READTHEDOCS_OUTPUT}"/epub -b epub
  - >-  # RTD requires only a single epub file to be in the output directory
    find "${READTHEDOCS_OUTPUT}"/epub
    -type f
    -not -name "${READTHEDOCS_PROJECT}.epub"
    -delete
    &&
    find "${READTHEDOCS_OUTPUT}"/epub
    -mindepth 1
    -type d
    -delete
    && ls -1 "${READTHEDOCS_OUTPUT}"/epub

...
