version: 2

formats:
  - epub
  - pdf

build:
  os: ubuntu-20.04
  tools:
    python: '3.10'

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    # Installation is needed in order to get the version string
    - method: pip
      path: .

    - requirements: docs/requirements.txt
