---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream8  # vanilla image!
    # name: quay.io/centos/centos:stream9  # vanilla image!
    # name: registry.fedoraproject.org/fedora:36  # vanilla image!
    # name: registry.access.redhat.com/ubi9/ubi:latest  # vanilla image!

# no longer required, we do the needful inline, but should still work if someone sets it
#  builder_image:
#    name: quay.io/centos/centos:stream9

dependencies:
  python_interpreter:
    package_system: python39
    python_path: /usr/bin/python3.9

  ansible_core:
    package_pip: https://github.com/ansible/ansible/archive/refs/tags/v2.13.2.tar.gz   # install from a GH ref tarball

  ansible_runner:
    package_pip: ansible-runner==2.2.1   # install from PyPI

  # FIXME: inline splat-as-string sucks, make separate keys for collections and roles
  galaxy: |
    collections:
    - community.windows  # depends on ansible.windows
    - ansible.utils  # injects lots of system and Python deps
    # - ansible.netcommon  # breaks on ubi9, shouldn't have python3-Cython as an install dep!

  python:
    - pywinrm

  system:
    - iputils [platform:rpm]

# FIXME: add more hook points for dynamic base/builder step injection, eg, manual builder build-time package installation
