---
- project:
    check:
      jobs: &id001
        # - ansible-builder-tox-integration
        - ansible-builder-build-container-image
        - ansible-tox-docs:
            vars:
                sphinx_build_dir: docs/build
        - ansible-tox-py38
        - github-workflows:
            files:
              - .github/workflows/.*
    gate:
      jobs: *id001
    post:
      jobs: &id002
        - ansible-builder-upload-container-image:
            vars:
              upload_container_image_promote: false
    periodic:
      jobs: *id002
